#!/bin/python

# libraries

from rich import print
import sys
from time import sleep

# lovely variables for output

infov = "[bold blue][INFO][/bold blue]"
debugv = "[bold magenta][DEBUG][/bold magenta]"
warningv = "[bold yellow][WARNING][/bold yellow]"
errorv = "[bold red][ERROR][/bold red]"

# check sys.argv (e.g. --debug)

try:

	if sys.argv[1] == "--debug" or sys.argv[1] == "-d":

		# turn off interface

		interface = False
		debug = True

		print(f"{debugv} DEBUG MODE IS ON")	
		print(f"{debugv} sys.argv = {sys.argv}")

		print(f"{debugv} you may choose to load the interface or not.")

	else:
		interface = True
		debug = False

except IndexError:
	interface = True
	debug = False

while True:
	if interface == True:
		# info for interface information

		print(f"{infov} Z.A.P.T-Interface is starting")
		print(f"{infov} if you do not see the interface, please try to debug it or report an issue in github.")
		print(f"{infov} github link: https://github.com/therealzakie/zaptInterface")

		# break in half

		break

	elif interface == False and debug == True:
		inputv = input("would you like to enable the interface?\n(Y/n) $ ")
		print(f"{debugv} inputv = {inputv}")
		inputv = inputv.lower()
		print(f"{debugv} inputv.lower() = {inputv}")

		if inputv == "y":
			print(f"{debugv} ZAPT-Interface enabled.")
			interface = True
		else:
			interface = False

	else:
		print(f"{errorv} uh oh! an oopsie happened somehow, please try running again.")
		print(f"{errorv} if it does not fix, try on another O.S. or try using the latest version.")
		
		t = 10
		
		print(f"{errorv} ZAPT-Interface will close in {t} seconds.")

		while t:
			mins, secs = divmod(t, 60)
			timer = '{:02d}:{:02d}'.format(mins, secs)
			print(timer, end='\r')  # Overwrite the line each second
			sleep(1)
			t -= 1

		print(f"{infov} Z.A.P.T-Interface has stopped")

		exit()