#!/bin/python

# libraries

from rich import print
import sys

# lovely variables for output

infov = "[bold blue][INFO][/bold blue]"
debugv = "[bold magenta][DEBUG][/bold magenta]"
warningv = "[bold yellow][WARNING][/bold yellow]"
errorv = "[bold red][ERROR][/bold red]"

# check sys.argv (e.g. --debug)

if sys.argv[1] == "--debug" or sys.argv[1] == "-d":

	# turn off interface

	interface = False
	debug = True

	print(f"{debugv} DEBUG MODE IS ON")	
	print(f"{debugv} sys.argv = {sys.argv}")

	print(f"{debugv} you may choose to load the interface or not.")

else:
	interface = True
	debug = False

while True:
	if interface == True:
		# info for interface information

		print(f"{infov} Z.A.P.T-Interface is starting")
		print(f"{infov} if you do not see the interface, please try to debug it or report an issue in github.")
		print(f"{infov} github link: https://github.com/therealzakie/zaptInterface")

		# break in half

		break

	elif interface == False:
		